import sys
import re


""" 
Mapping dict
provides a mapping between the old tree and
new tree, ensuring that data saved in one is
equivalent to data saved in the new tree.
""" 
mapping_dict = {
    "nr" : "fRunNumber",   
    "ne" : "fEventNumber",   
    "fidev" : "fIsFiducialEvent", 
    "bb0n" : "fIsbb0nCandidate", 
    "bb2n" : "fIsbb2nCandidate",  
    "alpha" : "fIsAlphaCandidate", 
    "nsite" : "fNumberOfSites", 
    "errec" : "fTotalRawEnergy", 
    "eprec" : "fTotalPurityCorrectedEnergy", 
    "ecrec" : "fTotalGridEfficiencyCorrectedEnergy", 
    "depth" : "fDepth", 
    "ecsum" : "fCorrectedEnergySum", 
    "header" : "fEventHeader.fHeaderString",        
    "svn_rev" : "fEventHeader.fSVNRevision",       
    "build_id" : "fEventHeader.fBuildID",      
    "compressionid" : "fEventHeader.fCompressionID", 
    "frameid" : "fEventHeader.fFrameID",       
    "framerev" : "fEventHeader.fFrameRevision",      
    "cc" : "fEventHeader.fCardCount",            
    "trigcount" : "fEventHeader.fTriggerCount",     
    "trigsec" : "fEventHeader.fTriggerSeconds",       
    "trigsub" : "fEventHeader.fTriggerMicroSeconds",       
    "trigdrift" : "fEventHeader.fTriggerDrift",     
    "sn" : "fEventHeader.fSumTriggerThreshold",            
    "sr" : "fEventHeader.fSumTriggerRequest",            
    "trigsum" : "fEventHeader.fSumTriggerValue",       
    "in" : "fEventHeader.fIndividualTriggerThreshold",            
    "ir" : "fEventHeader.fIndividualTriggerRequest",            
    "indsum" : "fEventHeader.fMaxValueChannel",        
    "trigchan" : "fEventHeader.fOfflineTriggerChannel",      
    "trigoff" : "fEventHeader.fTriggerOffset",       
    "ebit" : "fEventHeader.fFrameIsEmpty",          
    "src" : "fEventHeader.fTriggerSource",           
    "samplecount" : "fEventHeader.fSampleCount",   
    "g4ne" : "fEventHeader.fGeant4EventNumber",          
    "subne" : "fEventHeader.fGeant4SubEventNumber",         
    "is_mc" : "fEventHeader.fIsMonteCarloEvent",         
    "mcfid" : "fEventHeader.fMonteCarloFiducialFlag",         
    "muontag" : "fEventHeader.fTaggedAsMuon",            
    "muon_driftvelocity" : "fEventHeader.fMuonDriftVelocity", 
    "muon_purity" : "fEventHeader.fMuonPurity",       
    "muon_purity_err" : "fEventHeader.fMuonPurityError",    
    "qbeta" : "fMonteCarloData.fBetaDecayQValue", 
    "x0" : "fMonteCarloData.fPrimaryEventX",    
    "y0" : "fMonteCarloData.fPrimaryEventY",    
    "z0" : "fMonteCarloData.fPrimaryEventZ",    
    
    "totalph" : "fMonteCarloData.fTotalPhotons", 
    "hitsp1" : "fMonteCarloData.fTotalHitsArrayOne",  
    "hitsp2" : "fMonteCarloData.fTotalHitsArrayTwo",  
    "esalt" : "fMonteCarloData.fTotalEnergyInSalt",                 
    "eshield" : "fMonteCarloData.fTotalEnergyInShield",               
    "eoutcry" : "fMonteCarloData.fTotalEnergyInOuterCryostat",               
    "eincry" : "fMonteCarloData.fTotalEnergyInInnerCryostat",               
    "ehfe" : "fMonteCarloData.fTotalEnergyInHFE",                  
    "evessel" : "fMonteCarloData.fTotalEnergyInVessel",               
    "elxet" : "fMonteCarloData.fTotalEnergyInLiquidXe",                 
    "elxei" : "fMonteCarloData.fTotalIonizationEnergyInLiquidXe",                 
    "ecathode_photons" : "fMonteCarloData.fTotalEnergyOptPhotonsInCathode",      
    "eanodes_photons" : "fMonteCarloData.fTotalEnergyOptPhotonsInBothAnodes",       
    "ewire_supports_photons" : "fMonteCarloData.fTotalEnergyOptPhotonsInBothWireSupports",
    "ecathode_ring_photons" : "fMonteCarloData.fTotalEnergyOptPhotonsInCathodeRing", 
    "ereflector_photons" : "fMonteCarloData.fTotalEnergyOptPhotonsInTeflonReflector",    
    "eapd_frames_photons" : "fMonteCarloData.fTotalEnergyOptPhotonsInBothAPDFrames",   
    "elxe_photons" : "fMonteCarloData.fTotalEnergyOptPhotonsInLiquidXe",          
    "evessel_photons" : "fMonteCarloData.fTotalEnergyOptPhotonsInLiquidXeVessel",       
    "eremoved_apds_photons" : "fMonteCarloData.fTotalEnergyOptPhotonsInRemovedAPDs", 
    "efield_rings_photons" : "fMonteCarloData.fTotalEnergyOptPhotonsInFieldShapingRings",  
    "npart" :  "fMonteCarloData.GetNumParticleInformation()",
    "nq" :  "fMonteCarloData.GetNumPixelatedChargeDeposit()",
    "napd" :  "fMonteCarloData.GetNumAPDHits()",
    "idpart" : "fMonteCarloData.GetParticleInformation(%i)->fID", 
    "apart" :  "fMonteCarloData.GetParticleInformation(%i)->fAtomicNumber",  
    "epart" :  "fMonteCarloData.GetParticleInformation(%i)->fKineticEnergykeV",  
    "qpart" :  "fMonteCarloData.GetParticleInformation(%i)->fCharge",  
    "expart" : "fMonteCarloData.GetParticleInformation(%i)->fExcitedStatekeV", 


    "apd_hits" : "fMonteCarloData.GetAPDInfo(%i)->fNumHits", 
    "eapd" : "fMonteCarloData.GetAPDInfo(%i)->fEnergy",     
    "qapd" : "fMonteCarloData.GetAPDInfo(%i)->fCharge",     

    "ixq" : "fMonteCarloData.GetPixelatedChargeDeposit(%i)->fX", 
    "iyq" : "fMonteCarloData.GetPixelatedChargeDeposit(%i)->fY", 
    "izq" : "fMonteCarloData.GetPixelatedChargeDeposit(%i)->fZ", 
    "etq" : "fMonteCarloData.GetPixelatedChargeDeposit(%i)->fTotalEnergykeV", 
    "eiq" : "fMonteCarloData.GetPixelatedChargeDeposit(%i)->fTotalIonizationEnergykeV", 

    "c1sc" : "GetScintillationCluster(%i)->fCountsOnAPDPlaneOne",       
    "c1errsc" : "GetScintillationCluster(%i)->fCountsOnAPDPlaneOneError",    
    "c2sc" : "GetScintillationCluster(%i)->fCountsOnAPDPlaneTwo",       
    "c2errsc" : "GetScintillationCluster(%i)->fCountsOnAPDPlaneTwoError",    
    "c1sumsc" : "GetScintillationCluster(%i)->fCountsSumOnAPDPlaneOne",    
    "c1sumerrsc" : "GetScintillationCluster(%i)->fCountsSumOnAPDPlaneOneError", 
    "c2sumsc" : "GetScintillationCluster(%i)->fCountsSumOnAPDPlaneTwo",    
    "c2sumerrsc" : "GetScintillationCluster(%i)->fCountsSumOnAPDPlaneTwoError", 

    #"csc" : "GetScintillationCluster(%i).GetGangInfo(%i).fCounts",
    #"cerrsc" : "GetScintillationCluster(%i).GetGangInfo(%i).fCountsErr",
    #"chi2_APD1" : "GetScintillationCluster(%i).fChiSquaredAPDOne",  
    #"chi2_APD2" : "GetScintillationCluster(%i).fChiSquaredAPDTwo",  

    "xsc" : "GetScintillationCluster(%i)->fX",        
    "ysc" : "GetScintillationCluster(%i)->fY",        
    "zsc" : "GetScintillationCluster(%i)->fZ",        
    "tsc" : "GetScintillationCluster(%i)->fTime",        
    "rsc" : "GetScintillationCluster(%i)->fRadius",        
    "esc" : "GetScintillationCluster(%i)->fEnergy",        
    "algsc" : "GetScintillationCluster(%i)->fAlgorithmUsed",      

    "xcl" : "GetChargeCluster(%i)->fX",  
    "ycl" : "GetChargeCluster(%i)->fY",  
    "ucl" : "GetChargeCluster(%i)->fU",  
    "vcl" : "GetChargeCluster(%i)->fV",  
    "zcl" : "GetChargeCluster(%i)->fZ",  
    "dtcl" : "GetChargeCluster(%i)->fDriftTime", 
    "tcl" : "GetChargeCluster(%i)->fCollectionTime",  


    "ercl" : "GetChargeCluster(%i)->fRawEnergy",   
    "eccl" : "GetChargeCluster(%i)->fCorrectedEnergy",   
    "epcl" : "GetChargeCluster(%i)->fPurityCorrectedEnergy",   
    "eerrcl" : "GetChargeCluster(%i)->fCorrectedEnergyError", 
    "ncscl" : "GetChargeCluster(%i)->fNumberOfCollectionSignals",   
    "iu1cl" : "GetChargeCluster(%i)->fChanNumOfFirstSignal",   
    "iu2cl" : "GetChargeCluster(%i)->fChanNumOfSecondSignal",   
    "iu3cl" : "GetChargeCluster(%i)->fChanNumOfThirdSignal",   
    "iu4cl" : "GetChargeCluster(%i)->fChanNumOfFourthSignal",   
    "nvchcl" : "GetChargeCluster(%i)->fNumberOfVChannels",  
    "iv1cl" : "GetChargeCluster(%i)->fVChannelNumberOne",   
    "iv2cl" : "GetChargeCluster(%i)->fVChannelNumberTwo",   
    "dhalfcl" : "GetChargeCluster(%i)->fDetectorHalf", 
    "evcl" : "GetChargeCluster(%i)->fEnergyInVChannels",    


    "nusig" : "GetNumWires()",             
    "ncl" : "GetNumChargeClusters()",             
    "nsc" : "GetNumScintillationClusters()",             
    "usig_ch" : "GetUWireSignal(%i)->fChannel",             
    "usig_e" : "GetUWireSignal(%i)->fEnergy",              
    "usig_deltae" : "GetUWireSignal(%i)->fEnergyError",         
    "usig_t" : "GetUWireSignal(%i)->fTime",              
    "usig_deltat" : "GetUWireSignal(%i)->fTimeError",         
    "usig_baseline" : "GetUWireSignal(%i)->fBaseline",       
    "usig_deltabaseline" : "GetUWireSignal(%i)->fBaselineError",  
    "usig_chi2" : "GetUWireSignal(%i)->fChiSquare",           
    "nsig" : "GetWaveformData()->GetNumWaveforms()",

    "compton_e" : "fCompton.fEnergy",
    "compton_fom" : "fCompton.fFOM",
    "compton_ncl" : "fCompton.fNumClustersUsed",
    "compton_phi" : "fCompton.fHalfAnglePhi",
    "compton_phi_err" : "fCompton.fHalfAnglePhiErr",
    "compton_x1" : "fCompton.fX1",
    "compton_y1" : "fCompton.fY1",
    "compton_z1" : "fCompton.fZ1",
    "compton_dx1" : "fCompton.fX1Err",
    "compton_dy1" : "fCompton.fY1Err",
    "compton_dz1" : "fCompton.fZ1Err",
    "compton_x2" : "fCompton.fX2",
    "compton_y2" : "fCompton.fY2",
    "compton_z2" : "fCompton.fZ2",
    "compton_dx2" : "fCompton.fX2Err",
    "compton_dy2" : "fCompton.fY2Err",
    "compton_dz2" : "fCompton.fZ2Err",
     
    "ghcl" : "GetChargeCluster(%i)->fIsGhost",    
    "tdcl" : "GetChargeCluster(%i)->fIs3DCluster",    
    "fidcl" : "GetChargeCluster(%i)->fIsFiducial",   
    "nsample" : "GetWaveformData()->fNumSamples",
    #"chan" : "GetWaveformData().GetNumWaveforms()",
# Must handle data specially...
    #"nele" : "", 
    #"data" : "", 
    #"nqele" : "", 
    #"qdata" : "", 
    }

ignored = [
   "chan",
   "nsample",
   "nele",
   "data",
   "nqele",
   "qdata",
   "nsig",
   "header",
   "svn_rev",
   "build_id",
   "compressionid",
   "ssc", 
   "sssc", 
   "thsc", 
   ]
tref_list = [
   "usig_ichargecluster",
   "isccl",
   "iu1clcs",
   "iu2clcs",
   "iu3clcs",
   "iu4clcs",
   "scint_ichargecluster",
]
special_bool = {
}
not_yet_implemented = []
if __name__ == '__main__':
    oldfile = open(sys.argv[1]).read()
    for initial, final in mapping_dict.items():
        match_it = re.match("(.*)\(%i\)(.*)", final) 
        if match_it: 
            oldfile = re.sub(r'(->)%s\[(.+?)\]' % initial, r'\1%s(\2)%s' % (match_it.group(1), match_it.group(2)), oldfile)  
        else:
            oldfile = re.sub(r'(->)%s(\W+?)' % initial, r'\1%s\2' % final, oldfile)  
    print oldfile
